from __future__ import annotations

import json
import os
from typing import Any

import httpx
from dotenv import load_dotenv

from salinas_lab.security import redact


class ModelClientError(RuntimeError):
    pass


class ModelClient:
    def __init__(self, timeout: float = 120.0) -> None:
        load_dotenv()
        self.base_url = os.getenv("LM_STUDIO_BASE_URL", "http://localhost:1234/v1").rstrip("/")
        self.api_key = os.getenv("LM_STUDIO_API_KEY", "")
        self.timeout = timeout

    def chat(
        self,
        *,
        model: str,
        system: str,
        user: str,
        temperature: float = 0.4,
        max_tokens: int = 1800,
        _retried_empty: bool = False,
    ) -> str:
        if os.getenv("SALINAS_OFFLINE", "").lower() in {"1", "true", "yes"}:
            return self._offline_response(model=model)
        if os.getenv("OPENLOGOS_DEMO", "").lower() in {"1", "true", "yes"}:
            return self._demo_response(model=model, user=user)

        headers = {"Content-Type": "application/json"}
        if self.api_key:
            headers["Authorization"] = f"Bearer {self.api_key}"

        payload: dict[str, Any] = {
            "model": model,
            "messages": [
                {"role": "system", "content": system},
                {"role": "user", "content": user},
            ],
            "temperature": temperature,
            "max_tokens": max_tokens,
            "stream": False,
            "enable_thinking": False,
        }
        try:
            timeout = httpx.Timeout(
                timeout=self.timeout,
                connect=min(self.timeout, 10.0),
                read=self.timeout,
                write=min(self.timeout, 10.0),
                pool=min(self.timeout, 10.0),
            )
            with httpx.Client(timeout=timeout) as client:
                response = client.post(
                    f"{self.base_url}/chat/completions",
                    headers=headers,
                    json=payload,
                )
                response.raise_for_status()
                data = response.json()
                content = str(data["choices"][0]["message"].get("content") or "").strip()
                if not content and not _retried_empty:
                    retry_tokens = max(max_tokens * 3, 1200)
                    if retry_tokens > max_tokens:
                        return self.chat(
                            model=model,
                            system=system,
                            user=user,
                            temperature=temperature,
                            max_tokens=retry_tokens,
                            _retried_empty=True,
                        )
                if not content:
                    raise ModelClientError(
                        f"{model} returned an empty response from LM Studio after retry."
                    )
                return content
        except httpx.HTTPStatusError as exc:
            raise ModelClientError(redact(f"{model}: {self._safe_http_error(exc)}")) from exc
        except Exception as exc:
            if isinstance(exc, ModelClientError):
                raise
            raise ModelClientError(redact(f"{model}: {self._safe_error(exc)}")) from exc

    @staticmethod
    def extract_json(text: str) -> dict[str, Any]:
        cleaned = text.strip()
        if cleaned.startswith("```"):
            cleaned = cleaned.strip("`")
            cleaned = cleaned.removeprefix("json").strip()
        start = cleaned.find("{")
        end = cleaned.rfind("}")
        if start >= 0 and end > start:
            cleaned = cleaned[start : end + 1]
        return json.loads(cleaned)

    @staticmethod
    def _offline_response(model: str, error: str | None = None) -> str:
        reason = f" Model connection note: {error}" if error else ""
        return (
            f"Offline fallback generated by {model}.{reason}\n\n"
            "Findings:\n"
            "- The subject should be decomposed into use cases, feasibility questions, risks, "
            "and validation experiments.\n"
            "- The final report should clearly separate evidence from assumptions.\n"
            "- Further research should prioritize sources, user interviews, and small tests."
        )

    @staticmethod
    def _demo_response(model: str, user: str) -> str:
        return (
            f"Observation: Demo response from `{model}` for the submitted idea.\n"
            "Concern: This is deterministic demo mode, not a live LM Studio result.\n"
            "Next move: Configure LM Studio and run `/health` when you want real model output."
        )

    @staticmethod
    def _safe_http_error(exc: httpx.HTTPStatusError) -> str:
        status = exc.response.status_code
        if status == 401:
            return "LM Studio returned 401 Unauthorized. Check LM_STUDIO_API_KEY in .env."
        if status == 404:
            return "LM Studio endpoint or model was not found. Check base URL and model names."
        return f"LM Studio returned HTTP {status}."

    def _safe_error(self, exc: Exception) -> str:
        name = exc.__class__.__name__
        if "Connect" in name:
            return "LM Studio is not reachable from this machine."
        if "Timeout" in name:
            return f"LM Studio did not return a response within the {self.timeout:.0f}s timeout."
        return f"Local model call failed with {name}."

